# Generated by Django 5.2.6 on 2025-09-14 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenerationErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(default='Failed', max_length=5)),
                ('err_from', models.CharField(blank=True, max_length=30, null=True)),
                ('gemini_message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenerationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.CharField(max_length=50)),
                ('customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_tokens', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Started', 'STARTED'), ('Success', 'SUCCESS'), ('Failed', 'FAILED')], default='Pending', max_length=20)),
            ],
        ),
    ]
